/** Display-only French labels for Pipedream trigger names. IDs stay English. */

const EXACT: Record<string, string> = {
  "new email received": "Nouvel e-mail reçu",
  "new sent email": "Nouvel e-mail envoyé",
  "new labeled email": "Nouvel e-mail étiqueté",
  "new email matching search": "Nouvel e-mail correspondant à une recherche",
  "new attachment received": "Nouvelle pièce jointe reçue",
  "new email": "Nouvel e-mail",
  "new incoming email": "Nouvel e-mail entrant",
  "new spreadsheet row": "Nouvelle ligne de tableur",
  "new or updated spreadsheet row": "Ligne de tableur nouvelle ou mise à jour",
  "new worksheet": "Nouvelle feuille",
  "new spreadsheet": "Nouveau tableur",
  "new comment": "Nouveau commentaire",
  "new updates": "Nouvelles mises à jour",
  "new message in channels": "Nouveau message dans les canaux",
  "new direct message": "Nouveau message privé",
  "new mention": "Nouvelle mention",
  "new keyword mention": "Nouvelle mention de mot-clé",
  "new user": "Nouvel utilisateur",
  "new channel": "Nouveau canal",
  "new file": "Nouveau fichier",
  "new files": "Nouveaux fichiers",
  "new files in folder": "Nouveaux fichiers dans le dossier",
  "new folders": "Nouveaux dossiers",
  "new or modified files": "Fichiers nouveaux ou modifiés",
  "new or modified folders": "Dossiers nouveaux ou modifiés",
  "changes to specific files": "Modifications de fichiers spécifiques",
  "new presentation": "Nouvelle présentation",
  "new saved message": "Nouveau message enregistré",
  "new public message posted anywhere": "Nouveau message public",
  "new star added": "Nouveau favori ajouté",
  "reaction added": "Réaction ajoutée",
  "reaction removed": "Réaction retirée",
  "channel created": "Canal créé",
  "channel updates": "Mises à jour du canal",
  "new event": "Nouvel événement",
  "new or updated event": "Événement nouveau ou mis à jour",
  "new event matching search": "Nouvel événement correspondant à une recherche",
  "new calendar event": "Nouvel événement de calendrier",
  "event cancelled": "Événement annulé",
  "event canceled": "Événement annulé",
  "event start": "Début d’événement",
  "event ended": "Fin d’événement",
  "upcoming event": "Événement à venir",
  "new database item": "Nouvel élément de base de données",
  "updated database item": "Élément de base de données mis à jour",
  "new data source item": "Nouvel élément de source de données",
  "updated data source item": "Élément de source de données mis à jour",
  "new page": "Nouvelle page",
  "updated page": "Page mise à jour",
  "page updated": "Page mise à jour",
  "new issue": "Nouveau ticket",
  "new or updated issue": "Ticket nouveau ou mis à jour",
  "issue created": "Ticket créé",
  "issue updated": "Ticket mis à jour",
  "issue deleted": "Ticket supprimé",
  "new pull request": "Nouvelle pull request",
  "new or updated pull request": "Pull request nouvelle ou mise à jour",
  "new commit": "Nouveau commit",
  "new review request": "Nouvelle demande de relecture",
  "new star": "Nouveau favori",
  "new notification": "Nouvelle notification",
  "new release": "Nouvelle version",
  "new branch": "Nouvelle branche",
  "new discussion": "Nouvelle discussion",
  "new collaborator": "Nouveau collaborateur",
  "commit comment": "Commentaire de commit",
  "new record": "Nouvel enregistrement",
  "new records": "Nouveaux enregistrements",
  "new or modified records": "Enregistrements nouveaux ou modifiés",
  "new or modified records in view": "Enregistrements nouveaux ou modifiés dans la vue",
  "new, modified or deleted records": "Enregistrements nouveaux, modifiés ou supprimés",
  "new card": "Nouvelle carte",
  "card moved": "Carte déplacée",
  "card updated": "Carte mise à jour",
  "card archived": "Carte archivée",
  "new activity": "Nouvelle activité",
  "new label": "Nouvelle étiquette",
  "card due date reminder": "Rappel d’échéance de carte",
  "new submission": "Nouvelle soumission",
  "new form response": "Nouvelle réponse de formulaire",
  "new or updated form response": "Réponse de formulaire nouvelle ou mise à jour",
  "new contact": "Nouveau contact",
  "new company": "Nouvelle entreprise",
  "new deal": "Nouvelle affaire",
  "new ticket": "Nouveau ticket",
  "new engagement": "Nouvelle interaction",
  "contact updated": "Contact mis à jour",
  "company updated": "Entreprise mise à jour",
  "deal updated": "Affaire mise à jour",
  "new customer": "Nouveau client",
  "new payment": "Nouveau paiement",
  "new failed payment": "Paiement échoué",
  "new invoice": "Nouvelle facture",
  "checkout session completed": "Session de paiement terminée",
  "subscription updated": "Abonnement mis à jour",
  "canceled subscription": "Abonnement annulé",
  "cancelled subscription": "Abonnement annulé",
  "new message": "Nouveau message",
  "message deleted": "Message supprimé",
  "new guild member": "Nouveau membre du serveur",
  "new command received": "Nouvelle commande reçue",
  "new user added to channel": "Nouvel utilisateur ajouté au canal",
  "comment created": "Commentaire créé",
  "project update created": "Mise à jour de projet créée",
};

function isFrench(locale?: string): boolean {
  return (locale ?? "").toLowerCase().startsWith("fr");
}

function keyOf(value: string): string {
  return value.trim().replace(/\s+/g, " ").toLowerCase();
}

export function translateTriggerLabel(name: string, locale?: string): string {
  const raw = name.trim();
  if (!raw || !isFrench(locale)) return name;

  const instant = /\s*\(\s*instant\s*\)\s*$/i.test(raw);
  const core = raw.replace(/\s*\(\s*instant\s*\)\s*$/i, "").trim();
  const mapped = EXACT[keyOf(core)];
  if (!mapped) return name;
  return instant ? `${mapped} (instantané)` : mapped;
}
