-- Stack32 Phase 2 — runs and run_events.
-- No real execution yet: schema + read access only. Writes are server-side
-- (service role / trusted server actions in mock-AI mode).

create table public.runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  agent_id uuid not null references public.agents (id) on delete cascade,
  agent_version_id uuid references public.agent_versions (id) on delete set null,
  thread_id uuid,
  run_type text not null check (
    run_type in ('build', 'live', 'test', 'repair', 'ingestion')
  ),
  status text not null default 'queued' check (
    status in ('queued', 'running', 'completed', 'failed', 'canceled')
  ),
  input jsonb not null default '{}',
  output jsonb,
  error_code text,
  error_message text,
  provider text,
  model text,
  prompt_tokens integer,
  completion_tokens integer,
  estimated_cost numeric,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index runs_user_id_idx on public.runs (user_id);
create index runs_agent_id_created_at_idx on public.runs (agent_id, created_at desc);
create index runs_thread_id_idx on public.runs (thread_id);
create index runs_status_idx on public.runs (status);

create trigger set_runs_updated_at
  before update on public.runs
  for each row execute function public.set_updated_at();

create or replace function private.owns_run(run_uuid uuid)
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1 from public.runs r
    where r.id = run_uuid
      and r.user_id = (select auth.uid())
  );
$$;

revoke all on function private.owns_run(uuid) from public, anon;
grant execute on function private.owns_run(uuid) to authenticated, service_role;

alter table public.runs enable row level security;

create policy "runs_select_own"
  on public.runs for select
  to authenticated
  using ((select auth.uid()) = user_id and private.owns_agent(agent_id));

-- Users cannot forge runs, token counts, costs or statuses.
revoke insert, update, delete on public.runs from authenticated, anon;

-- ---------------------------------------------------------------------------
-- run_events — append-only event stream per run (future SSE reconnection).
-- ---------------------------------------------------------------------------
create table public.run_events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.runs (id) on delete cascade,
  sequence integer not null,
  event_type text not null,
  label text,
  payload jsonb not null default '{}',
  created_at timestamptz not null default now(),
  constraint run_events_run_id_sequence_key unique (run_id, sequence)
);

create index run_events_run_id_sequence_idx on public.run_events (run_id, sequence);

alter table public.run_events enable row level security;

create policy "run_events_select_own_run"
  on public.run_events for select
  to authenticated
  using (private.owns_run(run_id));

-- Append-only, server-side only for normal users.
revoke insert, update, delete on public.run_events from authenticated, anon;
